### ISSUE TITLE
Context specific content

### ISSUE THREAD

**Issue by bwiggs** [Contenda-Team/ai-ipsum#3]
First off, love this! 

It would be neat if this supported a context/industry/topic/domain input and the output would be generated using terms from that domain. Something like the old vegan ipsum site, although that seems to be dead now or https://baconipsum.com/

**Comment by cassidoo** [comment]
Woo hoo thanks!

Do you mean you being able to supplement what's in here with your own terms?

**Comment by bwiggs** [comment]
Hah, so i was confused on what I thought this project was doing. I didn't realize all the terms were hardcoded. :) 

I thought it was calling Chatgpt for a list of random ipsum like words, and I thought it would be neat to update that prompt to have a scope so it would generate words within some domain/context.

Sorry about that!

**Comment by cassidoo** [comment]
Ahhh yes this is why we said it "kind of" uses AI hahaha! No worries at all, cool idea though.
